language: ruby
rvm:
- 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: yE8xey0KEYK0Mywyj8yYXcckKmMmQzwYqwU/SH/kbigqklLZVrozzOed5AmGDKz/MfAe5fDdlPIhlqrh8rvyOhOiwCs5m7I2s4LP+rHcxOepdOz/Y3ghXuSnkUkAyMV7d32llQKaTpydLGL3jf6l3WM8Ux94RXyVYn460Mhwxax5GqmMRbjndlREfVPW0o6HBg61b4PL6jOcb7uXxjTUQcA/bg1KUvldu83DLF8Cw7JpcoTsWZ0FwHhGuzx0R0JJnj72M8eynEvAcXkBb1/x7UnaDXBYTn0tiFcdqGqKotztQG2unfS+LrjttFftSrI5ZLIhIXQo5XsKvkoglzDJpzs1oDrh1BGLoPkJ3qxHaKrTyUIBSpWjgkqQpS3pN6iZwgMQItKGBsvP3hm4OQfS+t6f1oEbMStHWhUrjgcJx4z6Kno/oT3BFjnv2TQoIain9/WVJ/nX5gvZqKoQ8zFG/cUd8F0tLhzriBMBQaOUv2YvBNGdi7WYvQXySY2SXpkglIZD5Px6VV7h2/6JgS6btdSpH4VORVblW5dY1WiO7iyxMlQQo0B/VDojAOZTEA89Rm0eTVMhIMqawLb3Hp3jXTcUpRHTLtYQazWSZ7XlH+Wr895Y2WrB9rz2D8NLbfXVWSn+4mt6jx0uHjj09GVvLuhOj9mZbtRhgPYlmHA+G+c=
  app: earmarked
  on:
    repo: TeamConchord/earmarked
    branch: 22-add-travis-ci
