language: ruby
rvm:
- 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: FkCNIMhl1++EHvcGOW35ijr9kWFdNvKV6SpreEshtRVbQ32/7m+RMYWaEa4sxhEq0kyEsAHxQDd+gzcu162s2pLvqgSWxcDmB7yTAXemjeXISje62IQuWTkygCl1zhUi4q3upOurVc1grXuUOM6xNLVt3g7RATFVFY/4lsHr02r5f9eTYSMVoAl1bMOeaDCgjCxsNGx49Y+SQ6yZOmZvQM0tXyfimj0fWL73Y2mye7ui9FZrieJQGbh/8aT+ZHTFuvb/vHWryIHQpWpCfmtu+WgWhc/e0cNB163wJQ03yshorPnKVOxesRlkrmpczUWwgx6ViNl5/RjD/67C64rwKplWcvoop2/OToMsgLwXBG2lHAGIKgPnkY05X8LRWyMiwqzQZgRVMRjX0TkXQyXRU4DzeWRVMr7wy++TeGeTaJZArPxPM4p8sA4ZD3KY7XGZ4+yPLc8T1U1Am8sFPp49VNIE1FyPboeP9k9lawBmkA/VI6boniwZgwwWPYI/eE113dosbfmIrpQavk6ylyJXSJX++VyQIFGQKQ6H52ZhZp2Irx2Wk5EWafs/6zFp+MCYxIXGIHi2ulRfLF8jrMDDwgBgqoaFv1gp4AARO7yOHKO9rs4zNoeycLUQ/pz3aVGBohfxr4QUkjDPQZ4C+R3Sw2UEB7Y+fgLhm3vO38jI1Sk=
  app: earmarked
  on:
    repo: TeamConchord/earmarked
