# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
production:
  stripe_api_key: sk_test_Rm26JZTaimisvqCz6VgcrTxH
  stripe_publishable_key: pk_test_h555RgcdhS9pcrWigzaAj2X8

test:
  PUBLISHABLE_KEY: pk_test_h555RgcdhS9pcrWigzaAj2X8
  SECRET_KEY: sk_test_Rm26JZTaimisvqCz6VgcrTxH

development:
  twilio_sid: "AC486b47e3554bd4a1701e2504bcbba534"
  twilio_token: "44086e06872417339c2c640925cc31a2"

production:
  twilio_sid: "AC486b47e3554bd4a1701e2504bcbba534"
  twilio_token: "44086e06872417339c2c640925cc31a2"
